# Generated by Django 6.0.6 on 2026-07-06 14:36

import analyst.models.user
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='BulletinTypeCatalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Flow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sna_flow_id', models.CharField(max_length=128)),
                ('domain', models.CharField(blank=True, max_length=255)),
                ('started_at', models.DateTimeField()),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.PositiveBigIntegerField(blank=True, null=True)),
                ('flow_action', models.CharField(blank=True, max_length=128)),
                ('mapping_method', models.CharField(choices=[('orientation', 'Orientation CSV'), ('subject_peer_fallback', 'Subject/Peer par défaut')], max_length=32)),
                ('direction', models.CharField(choices=[('outbound', 'Sortant'), ('inbound', 'Entrant'), ('internal', 'Interne'), ('external', 'Externe')], max_length=16)),
                ('src_ip', models.GenericIPAddressField(protocol='IPv4')),
                ('src_hostname', models.CharField(blank=True, max_length=255)),
                ('src_port', models.PositiveIntegerField(blank=True, null=True)),
                ('src_role', models.CharField(choices=[('client', 'Client'), ('server', 'Serveur'), ('unknown', 'Inconnu')], default='unknown', max_length=16)),
                ('src_location', models.CharField(blank=True, max_length=255)),
                ('src_asn', models.PositiveBigIntegerField(blank=True, null=True)),
                ('src_asn_assignment', models.CharField(blank=True, max_length=255)),
                ('src_bytes', models.PositiveBigIntegerField(blank=True, null=True)),
                ('src_packets', models.PositiveBigIntegerField(blank=True, null=True)),
                ('dst_ip', models.GenericIPAddressField(protocol='IPv4')),
                ('dst_hostname', models.CharField(blank=True, max_length=255)),
                ('dst_port', models.PositiveIntegerField(blank=True, null=True)),
                ('dst_role', models.CharField(choices=[('client', 'Client'), ('server', 'Serveur'), ('unknown', 'Inconnu')], default='unknown', max_length=16)),
                ('dst_location', models.CharField(blank=True, max_length=255)),
                ('dst_asn', models.PositiveBigIntegerField(blank=True, null=True)),
                ('dst_asn_assignment', models.CharField(blank=True, max_length=255)),
                ('dst_bytes', models.PositiveBigIntegerField(blank=True, null=True)),
                ('dst_packets', models.PositiveBigIntegerField(blank=True, null=True)),
                ('conversation_ip_a', models.GenericIPAddressField(editable=False, protocol='IPv4')),
                ('conversation_ip_b', models.GenericIPAddressField(editable=False, protocol='IPv4')),
                ('protocol', models.CharField(blank=True, max_length=32)),
                ('service', models.CharField(blank=True, max_length=128)),
                ('application', models.CharField(blank=True, max_length=255)),
                ('appliance', models.CharField(blank=True, max_length=255)),
                ('byte_rate', models.FloatField(blank=True, null=True)),
                ('packet_rate', models.FloatField(blank=True, null=True)),
                ('total_bytes', models.PositiveBigIntegerField(blank=True, null=True)),
                ('total_packets', models.PositiveBigIntegerField(blank=True, null=True)),
                ('tcp_connections', models.PositiveBigIntegerField(blank=True, null=True)),
                ('tcp_retransmissions', models.PositiveBigIntegerField(blank=True, null=True)),
                ('tcp_retransmission_ratio', models.FloatField(blank=True, null=True)),
                ('actions', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-started_at',),
            },
        ),
        migrations.CreateModel(
            name='Network',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('structure__name', 'name'),
            },
        ),
        migrations.CreateModel(
            name='RecommendationCatalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150, unique=True)),
                ('description', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='RiskCatalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Structure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('code', models.CharField(max_length=32, unique=True, validators=[django.core.validators.RegexValidator('^[A-Z0-9_-]+$', 'Utilisez des majuscules, chiffres, _ ou -.')])),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('display_name', models.CharField(blank=True, max_length=150)),
                ('role', models.CharField(choices=[('admin', 'Administrateur'), ('analyst', 'Analyste'), ('viewer', 'Lecteur')], default='viewer', max_length=16)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', analyst.models.user.EmailUserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Bulletin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reference_year', models.PositiveIntegerField(editable=False)),
                ('sequence_number', models.PositiveIntegerField(editable=False)),
                ('reference', models.CharField(editable=False, max_length=80, unique=True)),
                ('severity', models.CharField(choices=[('low', 'Faible'), ('medium', 'Moyenne'), ('high', 'Élevée'), ('critical', 'Critique')], max_length=16)),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('sent', 'Envoyé'), ('acknowledged', 'Pris en compte'), ('resolved', 'Résolu'), ('closed', 'Clôturé')], default='draft', max_length=16)),
                ('ip_signature', models.CharField(blank=True, db_index=True, editable=False, max_length=64)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_bulletins', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='deleted_bulletins', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='updated_bulletins', to=settings.AUTH_USER_MODEL)),
                ('structure', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bulletins', to='analyst.structure')),
            ],
            options={
                'ordering': ('-reference_year', '-sequence_number'),
            },
        ),
        migrations.CreateModel(
            name='BulletinResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('respondent_name', models.CharField(max_length=255)),
                ('respondent_email', models.EmailField(blank=True, max_length=254)),
                ('received_at', models.DateTimeField()),
                ('content', models.TextField()),
                ('bulletin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='analyst.bulletin')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bulletin_responses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-received_at',),
            },
        ),
        migrations.CreateModel(
            name='BulletinAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_filename', models.CharField(max_length=255)),
                ('stored_path', models.CharField(max_length=1024)),
                ('content_type', models.CharField(blank=True, max_length=255)),
                ('file_size_bytes', models.PositiveBigIntegerField()),
                ('file_sha256', models.CharField(max_length=64)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='analyst.bulletinresponse')),
            ],
        ),
        migrations.CreateModel(
            name='BulletinType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bulletin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='type_links', to='analyst.bulletin')),
                ('bulletin_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bulletin_links', to='analyst.bulletintypecatalog')),
            ],
        ),
        migrations.CreateModel(
            name='FlowImport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('processing', 'En cours'), ('completed', 'Terminé'), ('completed_with_errors', 'Terminé avec erreurs'), ('failed', 'Échoué')], default='pending', max_length=32)),
                ('original_filename', models.CharField(max_length=255)),
                ('stored_path', models.CharField(max_length=1024)),
                ('rejection_report_path', models.CharField(blank=True, max_length=1024)),
                ('file_sha256', models.CharField(max_length=64)),
                ('file_size_bytes', models.PositiveBigIntegerField()),
                ('detected_encoding', models.CharField(blank=True, max_length=32)),
                ('delimiter', models.CharField(default=',', max_length=1)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('period_start', models.DateTimeField(blank=True, null=True)),
                ('period_end', models.DateTimeField(blank=True, null=True)),
                ('total_rows', models.PositiveBigIntegerField(default=0)),
                ('accepted_rows', models.PositiveBigIntegerField(default=0)),
                ('inserted_flows', models.PositiveBigIntegerField(default=0)),
                ('reused_flows', models.PositiveBigIntegerField(default=0)),
                ('rejected_rows', models.PositiveBigIntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='flow_imports', to=settings.AUTH_USER_MODEL)),
                ('network', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='imports', to='analyst.network')),
            ],
            options={
                'ordering': ('-uploaded_at',),
            },
        ),
        migrations.CreateModel(
            name='FlowImportItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_row_number', models.PositiveBigIntegerField()),
                ('flow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='import_items', to='analyst.flow')),
                ('flow_import', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='analyst.flowimport')),
            ],
        ),
        migrations.AddField(
            model_name='flow',
            name='network',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flows', to='analyst.network'),
        ),
        migrations.CreateModel(
            name='NetworkCIDR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cidr', models.CharField(max_length=18)),
                ('label', models.CharField(blank=True, max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('network', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cidrs', to='analyst.network')),
            ],
            options={
                'ordering': ('network', 'cidr'),
            },
        ),
        migrations.CreateModel(
            name='PasswordResetToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_hash', models.CharField(max_length=128, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_reset_tokens', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reset_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='BulletinRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bulletin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendation_links', to='analyst.bulletin')),
                ('recommendation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bulletin_links', to='analyst.recommendationcatalog')),
            ],
        ),
        migrations.CreateModel(
            name='BulletinRisk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bulletin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risk_links', to='analyst.bulletin')),
                ('risk', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bulletin_links', to='analyst.riskcatalog')),
            ],
        ),
        migrations.AddField(
            model_name='network',
            name='structure',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='networks', to='analyst.structure'),
        ),
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=80)),
                ('entity_type', models.CharField(blank=True, max_length=80)),
                ('entity_id', models.CharField(blank=True, max_length=128)),
                ('occurred_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-occurred_at',),
                'indexes': [models.Index(fields=['occurred_at'], name='analyst_aud_occurre_915ea2_idx'), models.Index(fields=['actor', 'occurred_at'], name='analyst_aud_actor_i_b7b7af_idx'), models.Index(fields=['entity_type', 'entity_id'], name='analyst_aud_entity__2ac2d6_idx')],
            },
        ),
        migrations.CreateModel(
            name='BulletinIP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(protocol='IPv4')),
                ('role', models.CharField(choices=[('source', 'Source'), ('destination', 'Destination')], max_length=16)),
                ('bulletin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ip_addresses', to='analyst.bulletin')),
            ],
            options={
                'ordering': ('role', 'ip_address'),
                'indexes': [models.Index(fields=['ip_address'], name='analyst_bul_ip_addr_e3e927_idx')],
                'constraints': [models.UniqueConstraint(fields=('bulletin', 'ip_address'), name='uniq_ip_per_bulletin')],
            },
        ),
        migrations.AddIndex(
            model_name='bulletinresponse',
            index=models.Index(fields=['bulletin', 'received_at'], name='analyst_bul_bulleti_a6812d_idx'),
        ),
        migrations.AddConstraint(
            model_name='bulletintype',
            constraint=models.UniqueConstraint(fields=('bulletin', 'bulletin_type'), name='uniq_type_per_bulletin'),
        ),
        migrations.AddConstraint(
            model_name='flowimportitem',
            constraint=models.UniqueConstraint(fields=('flow_import', 'flow'), name='uniq_flow_per_import'),
        ),
        migrations.AddIndex(
            model_name='flowimport',
            index=models.Index(fields=['network', 'uploaded_at'], name='analyst_flo_network_b70d2e_idx'),
        ),
        migrations.AddIndex(
            model_name='flowimport',
            index=models.Index(fields=['file_sha256'], name='analyst_flo_file_sh_a0aa57_idx'),
        ),
        migrations.AddIndex(
            model_name='flowimport',
            index=models.Index(fields=['status'], name='analyst_flo_status_3b9518_idx'),
        ),
        migrations.AddIndex(
            model_name='flow',
            index=models.Index(fields=['network', 'started_at'], name='analyst_flo_network_6676c2_idx'),
        ),
        migrations.AddIndex(
            model_name='flow',
            index=models.Index(fields=['src_ip', 'started_at'], name='analyst_flo_src_ip_ff8f42_idx'),
        ),
        migrations.AddIndex(
            model_name='flow',
            index=models.Index(fields=['dst_ip', 'started_at'], name='analyst_flo_dst_ip_a5defc_idx'),
        ),
        migrations.AddIndex(
            model_name='flow',
            index=models.Index(fields=['direction', 'started_at'], name='analyst_flo_directi_a7a0fb_idx'),
        ),
        migrations.AddIndex(
            model_name='flow',
            index=models.Index(fields=['protocol'], name='analyst_flo_protoco_3dba6b_idx'),
        ),
        migrations.AddIndex(
            model_name='flow',
            index=models.Index(fields=['src_port'], name='analyst_flo_src_por_ea0733_idx'),
        ),
        migrations.AddIndex(
            model_name='flow',
            index=models.Index(fields=['dst_port'], name='analyst_flo_dst_por_c97558_idx'),
        ),
        migrations.AddIndex(
            model_name='flow',
            index=models.Index(fields=['conversation_ip_a', 'conversation_ip_b', 'started_at'], name='analyst_flo_convers_a5f8c5_idx'),
        ),
        migrations.AddConstraint(
            model_name='flow',
            constraint=models.UniqueConstraint(fields=('network', 'sna_flow_id'), name='uniq_sna_flow_per_network'),
        ),
        migrations.AddConstraint(
            model_name='networkcidr',
            constraint=models.UniqueConstraint(fields=('network', 'cidr'), name='uniq_cidr_per_network'),
        ),
        migrations.AddConstraint(
            model_name='bulletinrecommendation',
            constraint=models.UniqueConstraint(fields=('bulletin', 'recommendation'), name='uniq_recommendation_per_bulletin'),
        ),
        migrations.AddConstraint(
            model_name='bulletinrisk',
            constraint=models.UniqueConstraint(fields=('bulletin', 'risk'), name='uniq_risk_per_bulletin'),
        ),
        migrations.AddConstraint(
            model_name='network',
            constraint=models.UniqueConstraint(fields=('structure', 'name'), name='uniq_network_name_per_structure'),
        ),
        migrations.AddIndex(
            model_name='bulletin',
            index=models.Index(fields=['structure', 'ip_signature'], name='analyst_bul_structu_2e4193_idx'),
        ),
        migrations.AddIndex(
            model_name='bulletin',
            index=models.Index(fields=['status'], name='analyst_bul_status_e50c67_idx'),
        ),
        migrations.AddConstraint(
            model_name='bulletin',
            constraint=models.UniqueConstraint(fields=('structure', 'reference_year', 'sequence_number'), name='uniq_bulletin_sequence_per_year'),
        ),
    ]
