# Generated by Django 6.0.6 on 2026-07-10 15:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyst', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IPReputation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ip_address', models.GenericIPAddressField(protocol='IPv4', unique=True)),
                ('verdict', models.CharField(choices=[('malicious', 'Malveillant'), ('suspicious', 'Suspect'), ('clean', 'Propre'), ('unknown', 'Inconnu')], default='unknown', max_length=16)),
                ('score', models.FloatField(blank=True, null=True)),
                ('country', models.CharField(blank=True, max_length=2)),
                ('source_count', models.PositiveSmallIntegerField(default=0)),
                ('successful_source_count', models.PositiveSmallIntegerField(default=0)),
                ('flow_count', models.PositiveBigIntegerField(default=0)),
                ('first_seen_at', models.DateTimeField(blank=True, null=True)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('last_analyzed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ('verdict', '-score', '-last_analyzed_at', 'ip_address'),
                'indexes': [models.Index(fields=['verdict', '-score'], name='analyst_ipr_verdict_477bb7_idx'), models.Index(fields=['country'], name='analyst_ipr_country_ded55e_idx'), models.Index(fields=['source_count'], name='analyst_ipr_source__487857_idx'), models.Index(fields=['last_analyzed_at'], name='analyst_ipr_last_an_80ec2f_idx')],
            },
        ),
        migrations.CreateModel(
            name='IPReputationResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('abuseipdb', 'AbuseIPDB'), ('virustotal', 'VirusTotal'), ('shodan', 'Shodan')], max_length=32)),
                ('status', models.CharField(choices=[('success', 'Succès'), ('skipped', 'Ignoré'), ('error', 'Erreur')], default='success', max_length=16)),
                ('verdict', models.CharField(choices=[('malicious', 'Malveillant'), ('suspicious', 'Suspect'), ('clean', 'Propre'), ('unknown', 'Inconnu')], default='unknown', max_length=16)),
                ('score', models.FloatField(blank=True, null=True)),
                ('country', models.CharField(blank=True, max_length=2)),
                ('raw', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True)),
                ('analyzed_at', models.DateTimeField()),
                ('reputation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='analyst.ipreputation')),
            ],
            options={
                'ordering': ('-analyzed_at', 'source'),
                'indexes': [models.Index(fields=['source', 'status'], name='analyst_ipr_source_2acc66_idx'), models.Index(fields=['verdict', '-score'], name='analyst_ipr_verdict_f5343b_idx'), models.Index(fields=['analyzed_at'], name='analyst_ipr_analyze_02e25b_idx')],
                'constraints': [models.UniqueConstraint(fields=('reputation', 'source'), name='uniq_reputation_result_per_source')],
            },
        ),
    ]
