# Generated by Django 6.0.6 on 2026-07-13 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyst', '0004_bulletinfinding_peerobservation_peerobservationrisk_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='peerobservation',
            name='avg_duration_seconds',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='peerobservation',
            name='max_duration_seconds',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='peerobservation',
            name='total_duration_seconds',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddIndex(
            model_name='peerobservation',
            index=models.Index(fields=['-total_duration_seconds'], name='analyst_pee_total_d_f50ca1_idx'),
        ),
    ]
