# Generated by Django 6.0.6 on 2026-07-14 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analyst', '0006_structure_scoped_flow_imports'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='flowimport',
            name='analyst_flo_network_b70d2e_idx',
        ),
        migrations.RemoveField(
            model_name='flowimport',
            name='network',
        ),
    ]
