# Generated by Django 6.0.6 on 2026-07-14 14:46

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyst', '0008_flow_networks_and_bulletin_snapshots'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackgroundJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('flow_import', 'Import de flows'), ('ip_reputation', 'Analyse de réputation IP')], max_length=32)),
                ('status', models.CharField(choices=[('queued', 'En attente'), ('running', 'En cours'), ('completed', 'Terminé'), ('failed', 'Échoué')], default='queued', max_length=16)),
                ('task_id', models.CharField(blank=True, db_index=True, max_length=64)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('result', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True)),
                ('status_message', models.CharField(blank=True, max_length=255)),
                ('progress_current', models.PositiveBigIntegerField(default=0)),
                ('progress_total', models.PositiveBigIntegerField(default=0)),
                ('attempt_count', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='background_jobs', to=settings.AUTH_USER_MODEL)),
                ('flow_import', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='background_jobs', to='analyst.flowimport')),
                ('retried_from', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='retries', to='analyst.backgroundjob')),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['status', 'created_at'], name='analyst_bac_status_94a98f_idx'), models.Index(fields=['kind', 'created_at'], name='analyst_bac_kind_363b46_idx'), models.Index(fields=['flow_import', 'created_at'], name='analyst_bac_flow_im_3870dc_idx')],
            },
        ),
    ]
