# Generated by Django 6.0.6 on 2026-07-14 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyst', '0009_backgroundjob'),
    ]

    operations = [
        migrations.AddField(
            model_name='ipreputationresult',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='ipreputationresult',
            index=models.Index(fields=['source', 'expires_at'], name='analyst_ipr_source_64b361_idx'),
        ),
    ]
