# Generated by Django 6.0.6 on 2026-07-17 11:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyst', '0010_ipreputationresult_expires_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RiskIndicator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.TextField(unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.AddField(
            model_name='bulletinfinding',
            name='ioc_snapshot',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='bulletinfinding',
            name='risk_activity_snapshot',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='riskprofile',
            name='activity',
            field=models.CharField(blank=True, db_index=True, max_length=150),
        ),
        migrations.AddField(
            model_name='riskprofile',
            name='source_key',
            field=models.CharField(blank=True, editable=False, max_length=64, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='riskprofile',
            name='name',
            field=models.CharField(max_length=150),
        ),
        migrations.AddField(
            model_name='bulletinfinding',
            name='risk_indicator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bulletin_findings', to='analyst.riskindicator'),
        ),
        migrations.CreateModel(
            name='RiskProfileIndicator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indicator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='risk_profile_links', to='analyst.riskindicator')),
                ('risk_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indicator_links', to='analyst.riskprofile')),
            ],
            options={
                'ordering': ('risk_profile_id', 'indicator_id'),
                'constraints': [models.UniqueConstraint(fields=('risk_profile', 'indicator'), name='uniq_indicator_per_risk_profile')],
            },
        ),
        migrations.CreateModel(
            name='RiskProfilePortService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('port', models.PositiveIntegerField()),
                ('service', models.CharField(blank=True, max_length=64)),
                ('risk_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='port_services', to='analyst.riskprofile')),
            ],
            options={
                'ordering': ('port', 'service'),
                'indexes': [models.Index(fields=['port', 'service'], name='analyst_ris_port_d7f151_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('port__lte', 65535)), name='risk_profile_port_lte_65535'), models.UniqueConstraint(fields=('risk_profile', 'port', 'service'), name='uniq_port_service_per_risk_profile')],
            },
        ),
    ]
