# Generated by Django 6.0.6 on 2026-07-17 17:56

import django.db.models.deletion
from django.db import migrations, models


DEFAULT_RULES = (
    {
        "code": "long-ssh",
        "name": "Communication SSH anormalement longue",
        "description": "Signale une communication sur le port SSH dont la durée maximale dépasse le seuil.",
        "rule_type": "long_ssh",
        "severity": "high",
        "parameters": {"ports": [22], "min_duration_seconds": 1800},
    },
    {
        "code": "malicious-high-volume",
        "name": "Volume important avec une IP malveillante",
        "description": "Signale un volume journalier important entre un hôte et une peer déclarée malveillante.",
        "rule_type": "malicious_high_volume",
        "severity": "critical",
        "parameters": {"min_total_bytes": 10000000, "verdicts": ["malicious"]},
    },
    {
        "code": "repeated-peer",
        "name": "Connexions répétées vers une même peer",
        "description": "Signale un nombre élevé de flows journaliers entre un hôte et une peer.",
        "rule_type": "repeated_peer",
        "severity": "medium",
        "parameters": {"min_flow_count": 50},
    },
    {
        "code": "sensitive-port",
        "name": "Activité externe sur un port sensible",
        "description": "Signale une communication externe vers un service d’administration ou de partage sensible.",
        "rule_type": "sensitive_port",
        "severity": "high",
        "parameters": {"ports": [22, 23, 445, 3389, 5900, 5985, 5986], "min_flow_count": 1},
    },
    {
        "code": "multi-host-peer",
        "name": "Peer en communication avec plusieurs hôtes",
        "description": "Signale une peer non fiable observée sur plusieurs hôtes internes pendant la même journée.",
        "rule_type": "multi_host_peer",
        "severity": "high",
        "parameters": {
            "min_host_count": 5,
            "verdicts": ["malicious", "suspicious", "unknown"],
        },
    },
)


def create_default_rules(apps, schema_editor):
    DetectionRule = apps.get_model("analyst", "DetectionRule")
    for item in DEFAULT_RULES:
        code = item["code"]
        DetectionRule.objects.update_or_create(code=code, defaults={key: value for key, value in item.items() if key != "code"})


def remove_default_rules(apps, schema_editor):
    DetectionRule = apps.get_model("analyst", "DetectionRule")
    DetectionRule.objects.filter(code__in=[item["code"] for item in DEFAULT_RULES]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('analyst', '0011_riskindicator_bulletinfinding_ioc_snapshot_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backgroundjob',
            name='kind',
            field=models.CharField(choices=[('flow_import', 'Import de flows'), ('ip_reputation', 'Analyse de réputation IP'), ('detection', 'Détection SOC'), ('daily_aggregation', 'Agrégation journalière')], max_length=32),
        ),
        migrations.CreateModel(
            name='DetectionRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.SlugField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=160)),
                ('description', models.TextField(blank=True)),
                ('rule_type', models.CharField(choices=[('long_ssh', 'Communication SSH longue'), ('malicious_high_volume', 'Volume important avec une IP malveillante'), ('repeated_peer', 'Connexions répétées vers une peer'), ('sensitive_port', 'Activité sur un port sensible'), ('multi_host_peer', 'Peer en communication avec plusieurs hôtes')], max_length=40)),
                ('severity', models.CharField(choices=[('low', 'Faible'), ('medium', 'Moyenne'), ('high', 'Élevée'), ('critical', 'Critique')], max_length=16)),
                ('parameters', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('name', 'id'),
                'indexes': [models.Index(fields=['is_active', 'rule_type'], name='analyst_det_is_acti_ffc1c1_idx'), models.Index(fields=['severity', 'is_active'], name='analyst_det_severit_16bc4e_idx')],
            },
        ),
        migrations.CreateModel(
            name='DailyFlowAggregate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('dedupe_key', models.CharField(editable=False, max_length=64, unique=True)),
                ('host_ip', models.GenericIPAddressField(protocol='IPv4')),
                ('peer_ip', models.GenericIPAddressField(protocol='IPv4')),
                ('host_port', models.PositiveIntegerField(blank=True, null=True)),
                ('peer_port', models.PositiveIntegerField(blank=True, null=True)),
                ('protocol', models.CharField(blank=True, max_length=32)),
                ('service', models.CharField(blank=True, max_length=128)),
                ('direction', models.CharField(choices=[('outbound', 'Sortant'), ('inbound', 'Entrant'), ('internal', 'Interne'), ('external', 'Externe')], max_length=16)),
                ('peer_country', models.CharField(blank=True, max_length=255)),
                ('reputation_verdict', models.CharField(choices=[('malicious', 'Malveillant'), ('suspicious', 'Suspect'), ('clean', 'Propre'), ('unknown', 'Inconnu')], default='unknown', max_length=16)),
                ('reputation_score', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('flow_count', models.PositiveBigIntegerField(default=0)),
                ('total_bytes', models.PositiveBigIntegerField(default=0)),
                ('total_packets', models.PositiveBigIntegerField(default=0)),
                ('total_duration_seconds', models.PositiveBigIntegerField(default=0)),
                ('max_duration_seconds', models.PositiveBigIntegerField(blank=True, null=True)),
                ('first_seen_at', models.DateTimeField(blank=True, null=True)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('network', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='daily_flow_aggregates', to='analyst.network')),
                ('structure', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='daily_flow_aggregates', to='analyst.structure')),
            ],
            options={
                'ordering': ('-date', 'structure_id', 'host_ip', 'peer_ip'),
                'indexes': [models.Index(fields=['structure', 'date'], name='analyst_dai_structu_58dd44_idx'), models.Index(fields=['network', 'date'], name='analyst_dai_network_a01f95_idx'), models.Index(fields=['peer_ip', 'date'], name='analyst_dai_peer_ip_363373_idx'), models.Index(fields=['host_ip', 'date'], name='analyst_dai_host_ip_f78bbc_idx'), models.Index(fields=['reputation_verdict', 'date'], name='analyst_dai_reputat_482054_idx')],
            },
        ),
        migrations.CreateModel(
            name='DetectionHit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dedupe_key', models.CharField(editable=False, max_length=64, unique=True)),
                ('status', models.CharField(choices=[('open', 'Ouvert'), ('acknowledged', 'Pris en compte'), ('dismissed', 'Ignoré')], default='open', max_length=16)),
                ('severity', models.CharField(choices=[('low', 'Faible'), ('medium', 'Moyenne'), ('high', 'Élevée'), ('critical', 'Critique')], max_length=16)),
                ('title', models.CharField(max_length=255)),
                ('summary', models.TextField(blank=True)),
                ('observation_date', models.DateField()),
                ('host_ip', models.GenericIPAddressField(blank=True, null=True, protocol='IPv4')),
                ('peer_ip', models.GenericIPAddressField(blank=True, null=True, protocol='IPv4')),
                ('host_port', models.PositiveIntegerField(blank=True, null=True)),
                ('peer_port', models.PositiveIntegerField(blank=True, null=True)),
                ('service', models.CharField(blank=True, max_length=128)),
                ('peer_country', models.CharField(blank=True, max_length=255)),
                ('reputation_verdict', models.CharField(choices=[('malicious', 'Malveillant'), ('suspicious', 'Suspect'), ('clean', 'Propre'), ('unknown', 'Inconnu')], default='unknown', max_length=16)),
                ('reputation_score', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('flow_count', models.PositiveBigIntegerField(default=0)),
                ('host_count', models.PositiveBigIntegerField(default=0)),
                ('total_bytes', models.PositiveBigIntegerField(default=0)),
                ('total_packets', models.PositiveBigIntegerField(default=0)),
                ('total_duration_seconds', models.PositiveBigIntegerField(default=0)),
                ('first_seen_at', models.DateTimeField(blank=True, null=True)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('first_detected_at', models.DateTimeField(auto_now_add=True)),
                ('last_detected_at', models.DateTimeField(auto_now=True)),
                ('evidence', models.JSONField(blank=True, default=dict)),
                ('network', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='detection_hits', to='analyst.network')),
                ('structure', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detection_hits', to='analyst.structure')),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hits', to='analyst.detectionrule')),
            ],
            options={
                'ordering': ('-last_seen_at', '-last_detected_at'),
                'indexes': [models.Index(fields=['structure', 'status', '-last_seen_at'], name='analyst_det_structu_411277_idx'), models.Index(fields=['rule', 'observation_date'], name='analyst_det_rule_id_299d44_idx'), models.Index(fields=['peer_ip', '-last_seen_at'], name='analyst_det_peer_ip_ee2b93_idx'), models.Index(fields=['severity', 'status'], name='analyst_det_severit_a536f4_idx')],
            },
        ),
        migrations.RunPython(create_default_rules, remove_default_rules),
    ]
