# Generated by Django 6.0.6 on 2026-07-19 12:19

import django.db.models.deletion
from django.db import migrations, models


def migrate_activities(apps, schema_editor):
    ActivityCatalog = apps.get_model("analyst", "ActivityCatalog")
    BulletinActivity = apps.get_model("analyst", "BulletinActivity")
    BulletinType = apps.get_model("analyst", "BulletinType")
    BulletinTypeCatalog = apps.get_model("analyst", "BulletinTypeCatalog")
    RiskProfile = apps.get_model("analyst", "RiskProfile")

    activities_by_name = {}
    for old_activity in BulletinTypeCatalog.objects.all():
        activity, _ = ActivityCatalog.objects.get_or_create(
            name=old_activity.name,
            defaults={
                "description": old_activity.description,
                "is_active": old_activity.is_active,
            },
        )
        activities_by_name[old_activity.name.casefold()] = activity

    for profile in RiskProfile.objects.all():
        name = (profile.activity or "Non classée").strip() or "Non classée"
        activity = activities_by_name.get(name.casefold())
        if activity is None:
            activity = ActivityCatalog.objects.filter(name__iexact=name).first()
        if activity is None:
            activity = ActivityCatalog.objects.create(name=name)
        activities_by_name[name.casefold()] = activity
        profile.activity_ref_id = activity.id
        profile.save(update_fields=("activity_ref",))

    for link in BulletinType.objects.select_related("bulletin_type"):
        activity = activities_by_name.get(link.bulletin_type.name.casefold())
        if activity:
            BulletinActivity.objects.get_or_create(
                bulletin_id=link.bulletin_id,
                activity_id=activity.id,
            )


class Migration(migrations.Migration):

    dependencies = [
        ('analyst', '0012_alter_backgroundjob_kind_detectionrule_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityCatalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='BulletinActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='riskprofile',
            name='activity_ref',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='analyst.activitycatalog'),
        ),
        migrations.AddField(
            model_name='bulletinactivity',
            name='activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bulletin_links', to='analyst.activitycatalog'),
        ),
        migrations.AddField(
            model_name='bulletinactivity',
            name='bulletin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_links', to='analyst.bulletin'),
        ),
        migrations.AddConstraint(
            model_name='bulletinactivity',
            constraint=models.UniqueConstraint(fields=('bulletin', 'activity'), name='uniq_activity_per_bulletin'),
        ),
        migrations.RunPython(migrate_activities, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='riskprofile',
            name='activity',
        ),
        migrations.RenameField(
            model_name='riskprofile',
            old_name='activity_ref',
            new_name='activity',
        ),
        migrations.AlterField(
            model_name='riskprofile',
            name='activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='risk_profiles', to='analyst.activitycatalog'),
        ),
        migrations.DeleteModel(
            name='BulletinType',
        ),
        migrations.DeleteModel(
            name='BulletinTypeCatalog',
        ),
    ]
