# Generated by Django 6.0.6 on 2026-07-20 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyst', '0013_activitycatalog_bulletinactivity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='peerobservation',
            name='peer_country',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
