# Generated by Django 6.0.6 on 2026-07-20 08:57

from django.db import migrations, models
from django.db.models import Count


OBSERVATION_KEY = (
    "peer_reputation_id",
    "network_id",
    "host_ip",
    "host_port",
    "host_service",
    "host_port_category",
)


def deduplicate_observations_and_backfill_countries(apps, schema_editor):
    PeerObservation = apps.get_model("analyst", "PeerObservation")
    PeerObservationRisk = apps.get_model("analyst", "PeerObservationRisk")
    BulletinFinding = apps.get_model("analyst", "BulletinFinding")

    duplicate_keys = (
        PeerObservation.objects.values(*OBSERVATION_KEY)
        .annotate(row_count=Count("id"))
        .filter(row_count__gt=1)
    )
    for key in duplicate_keys.iterator():
        lookup = {field: key[field] for field in OBSERVATION_KEY}
        observations = list(
            PeerObservation.objects.filter(**lookup).order_by(
                "-total_duration_seconds", "-flow_count", "-total_bytes", "id"
            )
        )
        keeper, duplicates = observations[0], observations[1:]
        for duplicate in duplicates:
            for link in PeerObservationRisk.objects.filter(peer_observation_id=duplicate.id):
                existing = PeerObservationRisk.objects.filter(
                    peer_observation_id=keeper.id,
                    risk_profile_id=link.risk_profile_id,
                ).first()
                if existing:
                    link.delete()
                else:
                    PeerObservationRisk.objects.filter(pk=link.pk).update(peer_observation_id=keeper.id)

            for finding in BulletinFinding.objects.filter(peer_observation_id=duplicate.id):
                existing = BulletinFinding.objects.filter(
                    bulletin_id=finding.bulletin_id,
                    peer_observation_id=keeper.id,
                    risk_profile_id=finding.risk_profile_id,
                ).first()
                if existing:
                    finding.delete()
                else:
                    BulletinFinding.objects.filter(pk=finding.pk).update(peer_observation_id=keeper.id)
            duplicate.delete()

    for finding in BulletinFinding.objects.filter(peer_country_snapshot="").select_related(
        "peer_observation", "peer_observation__peer_reputation"
    ):
        country = (
            finding.peer_observation.peer_reputation.country
            or finding.peer_observation.peer_country
            or ""
        )
        if country:
            BulletinFinding.objects.filter(pk=finding.pk).update(peer_country_snapshot=country)


class Migration(migrations.Migration):

    dependencies = [
        ('analyst', '0014_peerobservation_peer_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bulletinfinding',
            name='peer_country_snapshot',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.RunPython(
            deduplicate_observations_and_backfill_countries,
            migrations.RunPython.noop,
        ),
        migrations.AddConstraint(
            model_name='peerobservation',
            constraint=models.UniqueConstraint(fields=('peer_reputation', 'network', 'host_ip', 'host_port', 'host_service', 'host_port_category'), name='uniq_peer_observation_endpoint', nulls_distinct=False),
        ),
    ]
