AUDIT_ACTIONS = {
    "AUTH_LOGIN_SUCCESS": "Connexion réussie",
    "AUTH_LOGIN_FAILURE": "Échec de connexion",
    "AUTH_LOGOUT": "Déconnexion",
    "AUTH_PASSWORD_RESET_CREATED": "Lien temporaire de réinitialisation créé",
    "AUTH_PASSWORD_RESET_USED": "Lien temporaire de réinitialisation utilisé",
    "USER_CREATED": "Utilisateur créé",
    "USER_UPDATED": "Utilisateur modifié",
    "USER_DELETED": "Utilisateur supprimé",
    "FLOW_IMPORT_PREVIEWED": "Prévalidation d'import CSV",
    "FLOW_IMPORT_CONFIRMED": "Import CSV confirmé",
    "FLOW_IMPORT_DELETED": "Import CSV supprimé",
    "FLOW_IMPORT_REJECTIONS_DOWNLOADED": "Rapport de rejets téléchargé",
    "FLOW_EXPORTED": "Flows exportés en CSV",
    "IP_TIMELINE_VIEWED": "Timeline IP consultée",
    "IP_REPUTATION_RECORDS_VIEWED": "Résultats réputation IP consultés",
    "IP_REPUTATION_CANDIDATES_VIEWED": "Candidats réputation IP consultés",
    "IP_REPUTATION_ANALYSIS_RUN": "Analyse réputation IP lancée",
    "BACKGROUND_JOB_STARTED": "Job asynchrone démarré",
    "BACKGROUND_JOB_COMPLETED": "Job asynchrone terminé",
    "BACKGROUND_JOB_FAILED": "Job asynchrone échoué",
    "BACKGROUND_JOB_RETRIED": "Job asynchrone relancé",
    "BACKGROUND_WORKER_START_REQUESTED": "Démarrage du worker demandé",
    "MALICIOUS_COMMUNICATIONS_ANALYZED": "Communications malveillantes corrélées",
    "DETECTION_RULE_CREATED": "Règle de détection créée",
    "DETECTION_RULE_UPDATED": "Règle de détection modifiée",
    "DETECTION_RUN_REQUESTED": "Analyse de détection lancée",
    "DETECTION_HIT_STATUS_UPDATED": "Statut d’une détection modifié",
    "DAILY_FLOW_AGGREGATION_REQUESTED": "Agrégation journalière lancée",
    "ACTIVITY_CREATED": "Activité créée",
    "ACTIVITY_UPDATED": "Activité modifiée",
    "ACTIVITY_DISABLED": "Activité désactivée",
    "BULLETIN_CREATED": "Bulletin créé",
    "BULLETIN_CREATED_FROM_FINDINGS": "Bulletin créé depuis des observations peer",
    "BULLETIN_DRAFT_CREATED_FROM_ASSISTANT": "Brouillon de bulletin créé par l'assistant",
    "BULLETIN_UPDATED": "Bulletin modifié",
    "BULLETIN_DELETED": "Bulletin supprimé",
    "BULLETIN_RESTORED": "Bulletin restauré",
    "BULLETIN_DUPLICATE_CHECKED": "Doublon bulletin vérifié",
    "BULLETIN_RESPONSE_CREATED": "Réponse bulletin créée",
    "BULLETIN_RESPONSE_UPDATED": "Réponse bulletin modifiée",
    "BULLETIN_RESPONSE_DELETED": "Réponse bulletin supprimée",
    "ANALYTICS_TOP_TALKERS_VIEWED": "Top talkers consulté",
    "ANALYTICS_TOP_CONVERSATIONS_VIEWED": "Top conversations consulté",
    "ANALYTICS_TOP_PORTS_PROTOCOLS_VIEWED": "Top ports/protocoles consulté",
    "DASHBOARD_OVERVIEW_VIEWED": "Dashboard consulté",
    "AUDIT_EVENTS_VIEWED": "Journal d'audit consulté",
    "SECURITY_PERMISSION_MATRIX_VIEWED": "Matrice de permissions consultée",
}


def audit_action_catalog() -> list[dict]:
    return [{"action": action, "label": label} for action, label in sorted(AUDIT_ACTIONS.items())]
