# Generated by Django 6.0.6 on 2026-07-13 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyst', '0002_ipreputation_ipreputationresult'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='bulletinip',
            name='uniq_ip_per_bulletin',
        ),
        migrations.AddField(
            model_name='bulletinip',
            name='note',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='bulletinip',
            name='port',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='bulletinip',
            constraint=models.UniqueConstraint(fields=('bulletin', 'ip_address', 'role', 'port'), name='uniq_ip_role_port_per_bulletin'),
        ),
    ]
