# Generated by Django 6.0.6 on 2026-07-13 12:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyst', '0003_remove_bulletinip_uniq_ip_per_bulletin_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BulletinFinding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('severity', models.CharField(blank=True, choices=[('low', 'Faible'), ('medium', 'Moyenne'), ('high', 'Élevée'), ('critical', 'Critique')], max_length=16)),
                ('impact_snapshot', models.TextField(blank=True)),
                ('recommendation_snapshot', models.TextField(blank=True)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='PeerObservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('host_ip', models.GenericIPAddressField(blank=True, null=True, protocol='IPv4')),
                ('host_port', models.PositiveIntegerField(blank=True, null=True)),
                ('host_service', models.CharField(blank=True, max_length=128)),
                ('host_port_category', models.CharField(blank=True, max_length=150)),
                ('first_seen_at', models.DateTimeField(blank=True, null=True)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('flow_count', models.PositiveBigIntegerField(default=0)),
                ('total_bytes', models.PositiveBigIntegerField(default=0)),
                ('total_packets', models.PositiveBigIntegerField(default=0)),
            ],
            options={
                'ordering': ('-last_seen_at', 'peer_reputation__ip_address', 'host_ip', 'host_port'),
            },
        ),
        migrations.CreateModel(
            name='PeerObservationRisk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('severity', models.CharField(blank=True, choices=[('low', 'Faible'), ('medium', 'Moyenne'), ('high', 'Élevée'), ('critical', 'Critique')], max_length=16)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='RiskProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150, unique=True)),
                ('impact', models.TextField()),
                ('recommendation', models.TextField()),
                ('default_severity', models.CharField(choices=[('low', 'Faible'), ('medium', 'Moyenne'), ('high', 'Élevée'), ('critical', 'Critique')], default='medium', max_length=16)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.AddField(
            model_name='bulletin',
            name='external_reference',
            field=models.CharField(blank=True, db_index=True, max_length=128),
        ),
        migrations.AddField(
            model_name='bulletin',
            name='network',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bulletins', to='analyst.network'),
        ),
        migrations.AddIndex(
            model_name='bulletin',
            index=models.Index(fields=['network', 'status'], name='analyst_bul_network_b40dcc_idx'),
        ),
        migrations.AddField(
            model_name='bulletinfinding',
            name='bulletin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='findings', to='analyst.bulletin'),
        ),
        migrations.AddField(
            model_name='peerobservation',
            name='network',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='peer_observations', to='analyst.network'),
        ),
        migrations.AddField(
            model_name='peerobservation',
            name='peer_reputation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observations', to='analyst.ipreputation'),
        ),
        migrations.AddField(
            model_name='bulletinfinding',
            name='peer_observation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bulletin_findings', to='analyst.peerobservation'),
        ),
        migrations.AddField(
            model_name='peerobservationrisk',
            name='peer_observation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risk_links', to='analyst.peerobservation'),
        ),
        migrations.AddIndex(
            model_name='riskprofile',
            index=models.Index(fields=['is_active', 'name'], name='analyst_ris_is_acti_7e4d5a_idx'),
        ),
        migrations.AddIndex(
            model_name='riskprofile',
            index=models.Index(fields=['default_severity'], name='analyst_ris_default_f1e344_idx'),
        ),
        migrations.AddField(
            model_name='peerobservationrisk',
            name='risk_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='observation_links', to='analyst.riskprofile'),
        ),
        migrations.AddField(
            model_name='bulletinfinding',
            name='risk_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bulletin_findings', to='analyst.riskprofile'),
        ),
        migrations.AddIndex(
            model_name='peerobservation',
            index=models.Index(fields=['network', 'host_ip'], name='analyst_pee_network_d52f1a_idx'),
        ),
        migrations.AddIndex(
            model_name='peerobservation',
            index=models.Index(fields=['host_port'], name='analyst_pee_host_po_07c57f_idx'),
        ),
        migrations.AddIndex(
            model_name='peerobservation',
            index=models.Index(fields=['host_service'], name='analyst_pee_host_se_983e5d_idx'),
        ),
        migrations.AddIndex(
            model_name='peerobservation',
            index=models.Index(fields=['-last_seen_at'], name='analyst_pee_last_se_055312_idx'),
        ),
        migrations.AddIndex(
            model_name='peerobservationrisk',
            index=models.Index(fields=['severity'], name='analyst_pee_severit_cf2f9a_idx'),
        ),
        migrations.AddConstraint(
            model_name='peerobservationrisk',
            constraint=models.UniqueConstraint(fields=('peer_observation', 'risk_profile'), name='uniq_risk_profile_per_peer_observation'),
        ),
        migrations.AddIndex(
            model_name='bulletinfinding',
            index=models.Index(fields=['severity'], name='analyst_bul_severit_78ae21_idx'),
        ),
        migrations.AddConstraint(
            model_name='bulletinfinding',
            constraint=models.UniqueConstraint(fields=('bulletin', 'peer_observation', 'risk_profile'), name='uniq_finding_per_bulletin_observation_risk'),
        ),
    ]
